#undef PACKAGE
#undef VERSION

#undef _POSIX_SOURCE

#undef STDC_HEADERS

#undef HAVE_STRING_H
#undef HAVE_STDLIB_H
#undef HAVE_CTYPE_H
#undef HAVE_TIME_H
#undef HAVE_ALLOCA_H

#undef HAVE_TIMEZONE
#undef HAVE_TM_GMTOFF
#undef HAVE_ISBLANK
#undef HAVE_STRFTIME
#undef HAVE_LOCALTIME
#undef HAVE_ALLOCA
